name:             'Oxygen'
url:              'http://www.oxygen.cat'
markdown:         rdiscount
pygments:         true

lsi:				true

baseurl:
permalink:        /:title

authors:
 oxygen:
  name: Oxygen
  display_name: Oxygen
  email: info@oxygen.cat
  web: http://www.oxygen.cat/

# Server
exclude:          ["LICENSE", "README.md",]
port:             9001

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://www.oxygen.cat/'
  media: 'assets/img'