name:             'Oxygen'
url:              'http://freecates.github.io'
markdown:         rdiscount
pygments:         true

baseurl:
permalink:        /:title

authors:
 oxygen:
  name: Oxygen
  display_name: Oxygen
  email: info@oxygen.cat
  web: http://www.oxygen.cat/

# Server
exclude:          ["LICENSE", "README.md",]
port:             9001